# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Hello World
      run : echo "HELLO WORLD"

    - name: Build
      run: npm install

    - name: Tests
      run: npm run test

    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=production --token=6Reh7fXieUh2oQ54cjknIFEZ

    - name: Build Project Artifacts
      run: vercel build --prod --token=6Reh7fXieUh2oQ54cjknIFEZ

    - name: Deploy Project Artifacts to Vercel
      run: vercel deploy --prebuilt --prod --token=6Reh7fXieUh2oQ54cjknIFEZ
